name: Docker package build on tags

on:
  push:
    tags:
      - '*'
  
jobs:
  build:
    env:
      TAG: ""
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file docker/Dockerfile \
          --tag docker.pkg.github.com/icubam/icubam/icubam-services:${GITHUB_REF##*/} \
          --tag docker.pkg.github.com/icubam/icubam/icubam-services:${{ github.sha }}
        # sanity check: run unit tests from within the container
        docker run -e JWT_SECRET=faketest --mount type=bind,source=$PWD/resources,target=/home/icubam/resources,readonly docker.pkg.github.com/icubam/icubam/icubam-services:${GITHUB_REF##*/} "conda init bash && conda activate icubam && pip install pytest && pytest"
    - name: docker login (GitHub)
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: docker push (GitHub)
      run:  |
        docker push docker.pkg.github.com/icubam/icubam/icubam-services:${GITHUB_REF##*/}
        docker push docker.pkg.github.com/icubam/icubam/icubam-services:${{ github.sha }}
