name: Python package

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.8.2-slim-buster
    env:
      # change the default cache directory for pip wheel
      # as $HOME is not writable.
      XDG_CACHE_HOME: /tmp/.cache/

    steps:
    - name: Install system dependencies
      run: |
        set -ex
        apt-get update
        apt-get install -y git curl sqlite3
    - uses: actions/checkout@v2
    - name: Cache wheels for dependencies
      id: cache-wheels
      uses: actions/cache@v1
      with:
        path: /tmp/.cache/pip
        key: ${{ runner.os }}-requirements-${{ hashFiles('requirements*.txt') }}
    - name: Install dependencies
      run: |
        set -ex
        which python
        python --version
        pip --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov mypy
    - name: Test with pytest
      env:
        JWT_SECRET: faketest
      run: |
        set -x
        pip install -e .
        pytest --cov=icubam --cov-report=xml --cov-report=html -r s
    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@v1"
      with:
        fail_ci_if_error: false
    - name: Typecheck with mypy
      run: |
        set -ex
        mypy -p icubam --ignore-missing-imports
    - name: Frontend tests
      env:
        JWT_SECRET: faketest
      run: |
        set -x
        python scripts/populate_db_fake.py --config=resources/config.toml
        pytest -v --cov=icubam --cov-report=xml --cov-report=html --icubam-config=resources/config.toml --run-server -r s frontend_tests/
    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@v1"
      with:
        fail_ci_if_error: false
