name: run shellcheck on all shell scripts

on: push

jobs:
  shellcheck:
    env:
      VERSION: "v0.7.1"
      SHA256_HASH: "64f17152d96d7ec261ad3086ed42d18232fcb65148b44571b564d688269d36c8"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install shellcheck
      run: |
        curl -fsSLO https://github.com/koalaman/shellcheck/releases/download/${VERSION}/shellcheck-${VERSION}.linux.x86_64.tar.xz && \
          echo "${SHA256_HASH}  shellcheck-${VERSION}.linux.x86_64.tar.xz" | sha256sum -c && \
          tar -xf shellcheck-${VERSION}.linux.x86_64.tar.xz && \
          sudo mv shellcheck-${VERSION}/shellcheck /usr/local/bin && \
          rm -fr shellcheck-${VERSION} shellcheck-${VERSION}.linux.x86_64.tar.xz
    - name: Run shellcheck
      run: |
        find . -type f -name '*.sh' | xargs shellcheck
